"""Add discount_amount to purchases

Revision ID: 0beb1c2c5c73
Revises: e07c45bb2038
Create Date: 2025-10-10 13:57:56.040962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0beb1c2c5c73'
down_revision = 'e07c45bb2038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_history', schema=None) as batch_op:
        #batch_op.add_column(sa.Column('old_status', sa.String(length=20), nullable=True))
        #batch_op.add_column(sa.Column('new_status', sa.String(length=20), nullable=True))
        #batch_op.add_column(sa.Column('history_data', sa.Text(), nullable=True))
        pass

    with op.batch_alter_table('purchase_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('product_vendor', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('product_category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('product_image', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('product_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_purchase_items_product_id', 'products', ['product_id'], ['id'])

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('estimated_delivery', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('customer_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('admin_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('admin_notes')
        batch_op.drop_column('customer_notes')
        batch_op.drop_column('estimated_delivery')
        batch_op.drop_column('discount_amount')

    with op.batch_alter_table('purchase_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('product_url')
        batch_op.drop_column('product_image')
        batch_op.drop_column('product_category')
        batch_op.drop_column('product_vendor')
        batch_op.drop_column('product_id')

    with op.batch_alter_table('purchase_history', schema=None) as batch_op:
        batch_op.drop_column('history_data')
        batch_op.drop_column('new_status')
        batch_op.drop_column('old_status')

    # ### end Alembic commands ###
