"""Add is_verified to users

Revision ID: 12afda54d1fd
Revises: 
Create Date: 2025-09-23 12:44:21.773003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12afda54d1fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('vendor_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('subcategory',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('currency',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.create_index('idx_category', ['category'], unique=False)
        batch_op.create_index('idx_description', ['description'], unique=False)
        batch_op.create_index('idx_ingram_part', ['ingram_part_number'], unique=False)
        batch_op.create_index('idx_vendor_name', ['vendor_name'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('idx_vendor_name')
        batch_op.drop_index('idx_ingram_part')
        batch_op.drop_index('idx_description')
        batch_op.drop_index('idx_category')
        batch_op.alter_column('currency',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=3),
               existing_nullable=True)
        batch_op.alter_column('subcategory',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('vendor_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
